title: Interpreting Robustness DRG
description: Class Website for Spring 2024 Interpreting Robustness DRG
theme: just-the-docs

url: https://RuoxiShang.github.io/interpretingrobustness

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/RuoxiShang/interpretingrobustness

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: 
    color: green
  note:
    title: 
    color: purple
  warning:
    title: Warning
    color: red